/**
 * STAGE B — PRODUCTION SURVIVAL GUIDE CONTENT (SME-curated, not SharePoint-verified).
 *
 * Generated from local-source-materials/terminology/defmet-survival-guide-v1.md,
 * an SME-curated terminology source explicitly provided as the content source
 * for the Survival Guide MVP (see docs/survival-guide-stage-b-validation-report.md).
 *
 * This is NOT SharePoint-verified content. Every entry below has
 * verificationStatus: 'SME-curated' and a single source of type
 * 'sme-curated' pointing at that file. No entry is marked 'verified', no
 * acronym expansion was inferred beyond what the source document states
 * explicitly, and no external/SharePoint content was consulted.
 *
 * Fields the source document did not provide per-term (plainLanguage,
 * whyItMatters, whereYouWillSeeIt, roleScope, processScope) are left as
 * empty string/array rather than invented — see the validation report for
 * the full per-field gap list.
 *
 * Stage B, Step 4: `SME_CURATED_GLOSSARY_ENTRIES` is now consumed directly
 * by `src/components/SurvivalGuideView.tsx` (rendered from the "Survival
 * Guide" tab in `src/App.tsx`). The UI renders only fields present here —
 * it does not fabricate or infer missing content — and always shows the
 * `SME-curated` label plus a `needsReview` flag per entry.
 *
 * `needsReview: true` was originally set for the terms the source document's
 * own Governance section (section 9) flagged as having acronym expansions
 * "not from a formal source" and recommended re-checking against an SME or
 * approved document before wide distribution: MGPC, RFC, xRFC, MSS, SM, SS,
 * DFX, DCL, SQC. Stage B.1 (below) resolved SS to `needsReview: false`
 * after direct SME confirmation; the other 8 remain `needsReview: true`.
 *
 * STAGE B.1 — GLOSSARY NORMALIZATION (see
 * docs/survival-guide-content-audit.md). A later pass added/enriched a
 * second set of terms (GL, NGL, SS, EDI, NCDD, CDD, ADC, ARS, YMC, DOR, EDX,
 * MGPC, DFX, GFA) from an SME's direct terminology confirmation given as
 * task instruction, not from the original source document. That
 * confirmation is recorded as its own `GlossarySource`
 * (`STAGE_B1_SME_SOURCE`, `sitePath: 'stage-b1-sme-instruction'`) so it is
 * never conflated with the original file's provenance. Where the Stage B.1
 * instruction agreed with or added to the original file content, both
 * sources are kept on the entry. Where it conflicted with previously
 * source-confirmed content (EDI's `fullName`, GFA's already-sourced
 * `fullName`), the conflict is recorded — not silently resolved — per
 * `docs/survival-guide-content-governance.md` rule 4, and the entry is kept
 * at `needsReview: true` pending human SME reconciliation. Every entry
 * remains `verificationStatus: 'SME-curated'`; none is upgraded to
 * `'verified'` by this pass.
 */
import type { GlossaryEntry, GlossarySource } from './types';

export const GLOSSARY_SOURCE_FILE = 'defmet-survival-guide-v1.md';

/**
 * Provenance marker for Stage B.1 content: terms/fields confirmed directly
 * by an SME as task instruction during the 2026-09-24 glossary
 * normalization pass, distinct from `GLOSSARY_SOURCE_FILE` (the original
 * ingested document). See docs/survival-guide-content-audit.md.
 */
const STAGE_B1_SME_SOURCE: GlossarySource = {
  sourceType: 'sme-curated',
  sitePath: 'stage-b1-sme-instruction',
  section: 'Stage B.1 glossary normalization — direct SME confirmation via task instruction (not a source document)',
  lastVerified: '2026-09-24',
  accessOutcome: 'accessible-fully-read',
};

/**
 * Provenance marker for Stage B.3 content: terms/fields drawn from
 * engineering onboarding notes and given as task instruction during the
 * 2026-09-24 "Engineer Notes Integration" pass, distinct from both
 * `GLOSSARY_SOURCE_FILE` and `STAGE_B1_SME_SOURCE`. See
 * docs/survival-guide-content-audit.md.
 */
const STAGE_B3_ENGINEER_NOTES_SOURCE: GlossarySource = {
  sourceType: 'sme-curated',
  sitePath: 'stage-b3-engineer-onboarding-notes',
  section: 'Stage B.3 engineer notes integration — engineering onboarding notes given as task instruction (not a source document)',
  lastVerified: '2026-09-24',
  accessOutcome: 'accessible-fully-read',
};

export const SME_CURATED_GLOSSARY_ENTRIES: GlossaryEntry[] = [
  {
    id: "edi",
    term: "EDI",
    abbreviation: "EDI",
    aliases: ["Equivalent Defect Impact", "Estimated Die Impact"],
    fullName: "Equivalent Defect Impact",
    category: "yield-defect",
    definition: "מדד שמתרגם דפקטים להשפעה על Yield. לא כל דפקט משפיע באופן זהה, ולכן מסתכלים על EDI ולא רק על מספר הדפקטים. Illustrative example (from source): דפקט אחד עשוי לתרום 0.01 EDI, בעוד דפקט אחר עשוי לתרום 3 EDI. Conflict (Stage B.1, not silently resolved — see docs/survival-guide-content-audit.md): the original source document explicitly names this 'Equivalent Defect Impact'; a later Stage B.1 SME instruction named it 'Estimated Die Impact' instead. Both are kept — as `fullName` and as an alias — pending human SME reconciliation of which is correct.",
    plainLanguage: "Estimate of how much the detected defects may hurt yield.",
    whyItMatters: "מאפשר לתעדף בעיות לפי השפעתן הצפויה על ה-Yield.",
    dailyWorkContext: [],
    whereYouWillSeeIt: ["דוחות PD", "סקירות Yield", "בדיקת Gaps", "Tracers ו-Disposition"],
    relatedTerms: ["Defect Count", "Baseline", "High EDI", "EDI Gap"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: true,
  },
  {
    id: "defect-count",
    term: "Defect Count",
    abbreviation: "DC",
    aliases: [],
    category: "yield-defect",
    definition: "מספר הדפקטים שנמדדו.",
    plainLanguage: "Counts אומרים כמה דפקטים נמצאו, אך לא בהכרח כמה הם משפיעים על Yield.",
    whyItMatters: "Wafer יכול להציג Defect Count גבוה אך השפעת EDI נמוכה יחסית, ולהפך.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI", "NCDD", "Classification"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "gfa",
    term: "GFA",
    abbreviation: "GFA",
    aliases: ["Geometric Failure Area"],
    fullName: "Geometric Failure Area",
    category: "yield-defect",
    definition: "אזור גאומטרי מסוים במפת ה-Wafer שבו קיימת הצטברות או תבנית של דפקטים. Examples (from source): 6 O'clock GFA; Center GFA; Edge GFA; Ring GFA. Conflict (Stage B.1, not silently resolved — see docs/survival-guide-content-audit.md): this fullName was stated directly by the original source document (not derived/inferred, and not among the 9 terms the source's own Governance section flagged as needing confirmation). A later Stage B.1 instruction nonetheless described GFA as \"pending SME verification\" with no fullName confirmed. The original source-confirmed fullName is kept rather than deleted; the entry is flagged for human SME reconciliation instead.",
    plainLanguage: "Spatial defect pattern/signature concept used by SSA.",
    whyItMatters: "צורת הפיזור עשויה לסייע בזיהוי קשר לתהליך, Tool, Chamber או נקודת מגע.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["CFA", "Wafer Map", "Morphology", "Segmentation"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: true,
  },
  {
    id: "cfa",
    term: "CFA",
    abbreviation: "CFA",
    aliases: ["Cluster Failure Area"],
    fullName: "Cluster Failure Area",
    category: "yield-defect",
    definition: "אשכול דפקטים המרוכז באזור מקומי. Examples (from source): Particle; Splash; Contamination",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["GFA", "Cluster", "Morphology", "Wafer Map"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "flyer",
    term: "Flyer",
    aliases: [],
    category: "yield-defect",
    definition: "Wafer חריג ביחס לשאר האוכלוסייה. Examples (from source): High EDI Flyer; High Defect Count Flyer",
    plainLanguage: "",
    whyItMatters: "Flyer עשוי להצביע על אירוע נקודתי, Bad Data או תחילת Signal הדורש בדיקה.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["High EDI", "OOC", "Excursion", "Bad Data"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "baseline",
    term: "Baseline",
    abbreviation: "BL",
    aliases: [],
    category: "yield-defect",
    definition: "הביצועים הנורמליים או הצפויים המשמשים כקו ייחוס להשוואה.",
    plainLanguage: "",
    whyItMatters: "Signal, Gap וחריגות נבחנים ביחס ל-Baseline.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI Gap", "OOC", "Chronic Gap"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "chronic-gap",
    term: "Chronic Gap",
    aliases: [],
    category: "yield-defect",
    definition: "פער ביצועים שקיים לאורך זמן ואינו אירוע נקודתי בלבד.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Baseline", "Main Issues", "Excursion", "Tactical Issue"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "excursion",
    term: "Excursion",
    aliases: [],
    category: "yield-defect",
    definition: "אירוע פתאומי או עלייה חריגה בדפקטיביות או בהשפעת Yield.",
    plainLanguage: "",
    whyItMatters: "Excursion עשוי לדרוש Containment, חקירה, תקשורת עם המודול ופעולות Recovery.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Tracer", "Root Cause", "Containment", "Quality Overview"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "tracer",
    term: "Tracer",
    aliases: [],
    category: "tracer-investigation",
    definition: "חקירה שנפתחת בעקבות Signal או חריגה כדי לזהות את מקור הבעיה ואת ה-Root Cause. Examples (from source): MGPC; OOC; High EDI; Hitback",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Root Cause", "Commonality", "RFC", "Containment"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "root-cause",
    term: "Root Cause",
    abbreviation: "RC",
    aliases: [],
    category: "tracer-investigation",
    definition: "הסיבה האמיתית והבסיסית שהובילה לבעיה או לדפקט.",
    plainLanguage: "",
    whyItMatters: "מטרת החקירה אינה רק לתאר את הבעיה, אלא לזהות גורם שניתן לפעול מולו.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Tracer", "Commonality", "Segmentation", "Recovery"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "commonality",
    term: "Commonality",
    aliases: [],
    category: "tracer-investigation",
    definition: "מאפיין, נתיב או שלב שכל ה-Wafers המושפעים עברו במשותף. Examples (from source): Tool; Chamber; Subentity; Recipe",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Root Cause", "Multipass", "Segmentation", "Entity"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "hitback",
    term: "Hitback",
    abbreviation: "HB",
    aliases: [],
    category: "tracer-investigation",
    definition: "בדיקה האם הדפקט היה קיים כבר בשכבה קודמת.",
    plainLanguage: "",
    whyItMatters: "מסייע להפריד בין מקור בשכבה הנוכחית לבין Defect שהגיע מתהליך קודם.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Previous Layer", "Escaped Defect", "Tracer"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "mgpc",
    term: "MGPC",
    aliases: [],
    category: "tracer-investigation",
    definition: "מודל או Signal סטטיסטי שמזהה תבנית משותפת במספר Wafers. Confirmed description (Stage B.1, no fullName invented): tracer type used to identify sustained separation from baseline and initiate defect response.",
    plainLanguage: "במקום להתמקד ב-Wafer חריג יחיד, מחפשים מספר נקודות או Wafers עם Pattern משותף ביחס ל-Baseline.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Signal", "Baseline", "Commonality", "Tracer"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: true,
  },
  {
    id: "high-edi",
    term: "High EDI",
    abbreviation: "High EDI",
    aliases: [],
    fullName: "High EDI",
    category: "tracer-investigation",
    definition: "Wafer בודד או Lot שעבר Threshold מוגדר של EDI. Note (from source): High EDI לא בהכרח מחייב MGPC. Confirmed (Stage B.3): signal generated by a single wafer or lot exceeding defined EDI thresholds.",
    plainLanguage: "One wafer has unusually high yield impact.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI", "Flyer", "Tracer", "Threshold", "OOC"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "ooc",
    term: "OOC",
    abbreviation: "OOC",
    aliases: ["Out Of Control"],
    fullName: "Out Of Control",
    category: "tracer-investigation",
    definition: "נקודה שנמצאת מחוץ לגבולות הבקרה הסטטיסטיים. Confirmed (Stage B.3): tracer or signal indicating a measurement outside statistical control limits.",
    plainLanguage: "Something is behaving outside normal limits.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["UCL", "LCL", "Baseline", "Tracer", "High EDI"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "false-signal",
    term: "False Signal",
    aliases: [],
    category: "tracer-investigation",
    definition: "Signal שנפתח, אך לאחר בדיקה לא נמצא שהוא מייצג בעיה אמיתית בתהליך או ב-Tool.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Signal", "Bad Data", "Tracer", "Root Cause"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "escaped-defect",
    term: "Escaped Defect",
    aliases: [],
    category: "tracer-investigation",
    definition: "דפקט שהיה אמור להתגלות בשלב מוקדם יותר אך לא נתפס והמשיך בתהליך.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Detection Gap", "Previous Layer", "Hitback", "Containment"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "segmentation",
    term: "Segmentation",
    aliases: [],
    category: "tracer-investigation",
    definition: "חלוקת הנתונים לקבוצות או נקודות תהליך כדי לזהות Root Cause או לצמצם את חלון החקירה. Examples (from source): POSTAVX; POSTPREC; PRE-SAT; POSTQM2",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Commonality", "Root Cause", "Process Step", "Hitback"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "pm",
    term: "PM",
    abbreviation: "PM",
    aliases: ["Preventive Maintenance"],
    fullName: "Preventive Maintenance",
    category: "recovery-tool-actions",
    definition: "טיפול תקופתי מתוכנן ב-Tool. Confirmed (Stage B.3): scheduled maintenance activity performed on a tool.",
    plainLanguage: "Routine maintenance intended to keep the tool healthy.",
    whyItMatters: "במהלך PM ה-Tool עשוי להיות מושבת, ולאחריו נדרשות פעולות Recovery בהתאם ל-Tool ולנוהל.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Recovery", "CM", "Station Monitor"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "cm",
    term: "CM",
    abbreviation: "CM",
    aliases: ["Corrective Maintenance"],
    fullName: "Corrective Maintenance",
    category: "recovery-tool-actions",
    definition: "טיפול תחזוקתי שמבוצע בעקבות תקלה או בעיה שהתגלתה.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["PM", "Recovery", "Tool Restriction"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "rfc",
    term: "RFC",
    aliases: [],
    category: "recovery-tool-actions",
    definition: "סט פעולות Recovery ו-Validation המתבצעות בעקבות Tracer או אירוע Tool. Clarification (from source): RFC אינו Recipe. הפעולות המדויקות תלויות ב-CEID, ב-Tool, בסוג האירוע ובנוהל המאושר.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["xRFC", "Recovery", "GO", "NO GO", "GL"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: true,
  },
  {
    id: "xrfc",
    term: "xRFC",
    aliases: [],
    category: "recovery-tool-actions",
    definition: "RFC מורחב הכולל פעולות או בדיקות נוספות בהתאם לנוהל המאושר.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["RFC", "Recovery", "Station Monitor"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: true,
  },
  {
    id: "recovery",
    term: "Recovery",
    aliases: [],
    category: "recovery-tool-actions",
    definition: "מכלול הפעולות שנועדו להחזיר Tool למצב תקין ולייצור, בהתאם לנוהל המאושר.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["RFC", "PM", "CM", "GO", "GL"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "go",
    term: "GO",
    aliases: [],
    fullName: "GO",
    category: "recovery-tool-actions",
    definition: "החלטה המאפשרת להחזיר את ה-Tool לייצור לאחר שהתקיימו תנאי השחרור הרלוונטיים. Confirmed (Stage B.3): decision indicating that a tool passed all required recovery, monitor, or gating checks and may return to production.",
    plainLanguage: "The tool is approved to run wafers again.",
    whyItMatters: "Used after tracer response and recovery activities.",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["NO GO", "GL", "Recovery", "Disposition", "RFC"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "no-go",
    term: "NO GO",
    aliases: [],
    fullName: "NO GO",
    category: "recovery-tool-actions",
    definition: "החלטה שלא לאפשר ל-Tool לחזור לייצור, משום שתנאי השחרור לא התקיימו. Confirmed (Stage B.3): decision indicating that a tool did not pass required checks and may not return to production.",
    plainLanguage: "The tool must remain restricted until additional actions are completed.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["GO", "Recovery", "RFC", "Tool Restriction", "GL"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "gl",
    term: "GL",
    abbreviation: "GL",
    aliases: ["Gating Lot"],
    fullName: "Gating Lot",
    category: "recovery-tool-actions",
    definition: "Lot המשמש לקבלת החלטה האם ה-Tool יכול לחזור לייצור. Confirmed (Stage B.1): lot used to determine whether a tool or process can return to production after recovery activity, RFC or tracer response.",
    plainLanguage: "The decision lot. Its results are used for GO / NO-GO decisions.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["GO", "NO GO", "NGL", "Disposition", "RFC"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "ngl",
    term: "NGL",
    abbreviation: "NGL",
    aliases: ["Non-Gating Lot", "Non Gating Lot"],
    fullName: "Non-Gating Lot",
    category: "recovery-tool-actions",
    definition: "Lot המשמש למעקב או מידע, אך אינו קובע לבדו את החלטת השחרור. Confirmed (Stage B.1): lot used for follow-up monitoring after recovery or tracer activity but does not block tool release.",
    plainLanguage: "A monitoring lot that provides extra confidence but is not the lot that decides tool release.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["GL", "Follow-Up Lot", "Recovery"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "follow-up-lot",
    term: "Follow-Up Lot",
    aliases: [],
    category: "recovery-tool-actions",
    definition: "Lot שמתויג לצורך מעקב לאחר Recovery, פעילות Tool או אירוע.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["GL", "NGL", "Disposition"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "sm",
    term: "SM",
    abbreviation: "SM",
    aliases: ["SurfaceScan Monitor"],
    fullName: "SurfaceScan Monitor",
    category: "recovery-tool-actions",
    definition: "בדיקת מצב Tool באמצעות Monitor Wafers וסריקת פני שטח.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Station Monitor", "SS", "MSS", "Monitor Wafer"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: true,
  },
  {
    id: "mss",
    term: "MSS",
    abbreviation: "MSS",
    aliases: ["Monitor Surface Scan"],
    fullName: "Monitor Surface Scan",
    category: "recovery-tool-actions",
    definition: "בדיקה נוספת של ניקיון או יציבות התהליך באמצעות Monitor Surface Scan. Note (from source): המשמעות או היישום המדויק עשויים להשתנות בין מודולים; יש לפעול לפי הנוהל המאושר.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["SM", "SS", "Recovery"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: true,
  },
  {
    id: "dfx",
    term: "DFX",
    aliases: [],
    category: "recovery-tool-actions",
    definition: "Defectivity check או scan שמבוצע לאחר פעילות Tool לצורך Validation. Confirmed description (Stage B.1, no fullName invented): surface-defect related monitor/check used in recovery and response flows.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Recovery", "SS", "Station Monitor"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: true,
  },
  {
    id: "gp",
    term: "GP",
    abbreviation: "GP",
    aliases: ["Golden Procedure"],
    fullName: "Golden Procedure",
    category: "recovery-tool-actions",
    definition: "פעילות או רצף פעולות מוגדר ומאושר.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["RFC", "Procedure", "Recovery"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "main-issues",
    term: "Main Issues",
    aliases: [],
    category: "pd-daily-work",
    definition: "הגורמים המרכזיים שאחראים לפער ה-EDI במשמרת או בתקופת הדיווח.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI Gap", "Layer Gap", "Defect Gap", "Lots Gap"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "defect-gap",
    term: "Defect Gap",
    aliases: [],
    category: "pd-daily-work",
    definition: "פער ביצועים שמיוחס לסוג Defect מסוים.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI Gap", "Main Issues", "Layer Gap"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "layer-gap",
    term: "Layer Gap",
    aliases: [],
    category: "pd-daily-work",
    definition: "פער ביצועים שמיוחס לשכבה מסוימת.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI Gap", "Defect Gap", "Main Issues"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "lots-gap",
    term: "Lots Gap",
    aliases: [],
    category: "pd-daily-work",
    definition: "מספר או קבוצת ה-Lots האחראים לפער הנבדק.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Main Issues", "Layer Gap", "EDI Gap"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "wtd",
    term: "WTD",
    abbreviation: "WTD",
    aliases: ["Week To Date"],
    fullName: "Week To Date",
    category: "pd-daily-work",
    definition: "נתונים מצטברים מתחילת השבוע ועד נקודת הזמן הנוכחית בדוח. Confirmed (Stage B.3): data accumulated from the beginning of the current week until now.",
    plainLanguage: "Everything counted since the start of the week.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "mtd",
    term: "MTD",
    abbreviation: "MTD",
    aliases: ["Month To Date"],
    fullName: "Month To Date",
    category: "pd-daily-work",
    definition: "נתונים מצטברים מתחילת החודש ועד נקודת הזמן הנוכחית בדוח.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "qtd",
    term: "QTD",
    abbreviation: "QTD",
    aliases: ["Quarter To Date"],
    fullName: "Quarter To Date",
    category: "pd-daily-work",
    definition: "נתונים מצטברים מתחילת הרבעון ועד נקודת הזמן הנוכחית בדוח.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "bad-data",
    term: "Bad Data",
    aliases: [],
    category: "pd-daily-work",
    definition: "מדידה או נתון שנחשדים כלא מהימנים או שאינם מייצגים את מצב התהליך בפועל.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["False Signal", "Data Validation", "Flyer"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "quality-overview",
    term: "Quality Overview",
    aliases: [],
    category: "pd-daily-work",
    definition: "ריכוז של אירועי איכות פתוחים, השפעתם וסטטוס הטיפול בהם.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Open Issue", "Excursion", "QEF", "Disposition"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "open-issue",
    term: "Open Issue",
    aliases: [],
    category: "pd-daily-work",
    definition: "בעיה שעדיין נמצאת בחקירה, טיפול או מעקב.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Quality Overview", "Action Item", "Owner", "Next Step"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "dispo",
    term: "Dispo",
    abbreviation: "Dispo",
    aliases: ["Disposition"],
    fullName: "Disposition",
    category: "pd-daily-work",
    definition: "החלטה מה לעשות עם Lot, Tool או אירוע על בסיס הנתונים והנוהל הרלוונטי.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["GO", "NO GO", "GL", "Hold", "Release"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "ceid",
    term: "CEID",
    aliases: [],
    category: "process-manufacturing",
    definition: "מזהה של Process Entity או Tool Family. Examples (from source): NST; AVX; SAT; GTX",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Entity", "Tool Family", "Subentity"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "entity",
    term: "Entity",
    aliases: [],
    category: "process-manufacturing",
    definition: "Tool מסוים או מופע ציוד ספציפי. Illustrative example (from source): `SAT123_CHB`",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["CEID", "Subentity", "Chamber"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "subentity",
    term: "Subentity",
    aliases: [],
    category: "process-manufacturing",
    definition: "רכיב או יחידת משנה בתוך Tool. Examples (from source): Chamber; Cell; PEM; LL",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Entity", "Commonality", "Chamber"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "cell",
    term: "Cell",
    aliases: [],
    category: "process-manufacturing",
    definition: "אזור או יחידת עבודה בתוך Tool.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "pem",
    term: "PEM",
    abbreviation: "PEM",
    aliases: ["Process Equipment Module"],
    fullName: "Process Equipment Module",
    category: "process-manufacturing",
    definition: "מודול ציוד תהליך בתוך Tool.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "ll",
    term: "LL",
    abbreviation: "LL",
    aliases: ["Loadlock"],
    fullName: "Loadlock",
    category: "process-manufacturing",
    definition: "אזור ב-Tool המשמש להעברת Wafers בין הסביבה החיצונית לסביבת התהליך.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "por",
    term: "POR",
    abbreviation: "POR",
    aliases: ["Process Of Record"],
    fullName: "Process Of Record",
    category: "process-manufacturing",
    definition: "התהליך הרשמי והמאושר לייצור.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Non-POR", "Recipe", "QEF"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "non-por",
    term: "Non-POR",
    aliases: [],
    category: "process-manufacturing",
    definition: "פעילות או תהליך שרצים מחוץ ל-Process Of Record המאושר. Note (from source): פעילות Non-POR עשויה לדרוש אישור או תיעוד רלוונטי בהתאם לנוהל.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["POR", "Pilot", "QEF"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "pilot",
    term: "Pilot",
    aliases: [],
    fullName: "Pilot",
    category: "process-manufacturing",
    definition: "ניסוי Process או שינוי מבוקר שנועד לבדוק השפעה של תנאי או פעילות. Confirmed (Stage B.3): controlled process or tool change performed to evaluate impact versus baseline behavior.",
    plainLanguage: "A temporary experiment performed on production tools or process conditions.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["DOE", "Split Lot", "Non-POR", "Baseline"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "split-lot",
    term: "Split Lot",
    aliases: [],
    category: "process-manufacturing",
    definition: "Lot שמחולק למספר תנאים או מסלולים לצורך השוואה או ניסוי.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["DOE", "Pilot"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "doe",
    term: "DOE",
    abbreviation: "DOE",
    aliases: ["Design Of Experiments"],
    fullName: "Design Of Experiments",
    category: "process-manufacturing",
    definition: "ניסוי סטטיסטי מתוכנן לבדיקת השפעת משתנים ותנאים.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Pilot", "Split Lot", "Root Cause"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "recipe",
    term: "Recipe",
    aliases: [],
    category: "process-manufacturing",
    definition: "סט פרמטרים והגדרות שמגדיר כיצד תהליך או מדידה מבוצעים עבור מוצר, שכבה או Tool. Clarification (from source): קיימים Recipes לתהליך, Scan ו-Review. יש לפעול לפי הגרסה המאושרת והרלוונטית.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["POR", "Process Step", "Tool"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "scan",
    term: "Scan",
    aliases: [],
    category: "measurement-analysis",
    definition: "שלב הסריקה שבו ציוד Metrology מזהה Defect Candidates על ה-Wafer.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Review", "Classification", "Optical Inspection"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "review",
    term: "Review",
    aliases: [],
    category: "measurement-analysis",
    definition: "שלב שבו נבדקת דגימה מהדפקטים שהתגלו ונאספים Images או מידע נוסף.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Scan", "Classification", "SEM Review"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "classification",
    term: "Classification",
    aliases: [],
    category: "measurement-analysis",
    definition: "סיווג Defects לפי מצב, סוג, Morphology או קטגוריה מוגדרת.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["ADC", "Manual Classification", "FineBin"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "adc",
    term: "ADC",
    abbreviation: "ADC",
    aliases: ["Automatic Defect Classification"],
    fullName: "Automatic Defect Classification",
    category: "measurement-analysis",
    definition: "סיווג אוטומטי של דפקטים באמצעות מערכת או מודל Classification. Confirmed (Stage B.1): system that automatically classifies defect images and assigns confidence scores.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Classification", "Manual Classification", "FineBin"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "manual-classification",
    term: "Manual Classification",
    aliases: [],
    category: "measurement-analysis",
    definition: "סיווג דפקטים ידני על ידי משתמש.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["ADC", "Classification", "ICE"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "finebin",
    term: "FineBin",
    aliases: [],
    category: "measurement-analysis",
    definition: "תת-סיווג מדויק יותר של Defect לפי מאפיינים כמו Morphology או Configuration.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Classification", "ADC"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "edx",
    term: "EDX",
    abbreviation: "EDX",
    aliases: ["Energy Dispersive X-ray"],
    fullName: "Energy Dispersive X-ray",
    category: "measurement-analysis",
    definition: "בדיקה המסייעת בזיהוי החומר או ההרכב שממנו עשוי הדפקט. Confirmed (Stage B.1): analysis method used to determine elemental composition.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Review", "Root Cause", "Material Analysis"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "original-adders",
    term: "Original Adders",
    aliases: ["Adders Only"],
    category: "measurement-analysis",
    definition: "דפקטים שמיוחסים לשכבה הנוכחית ולא זוהו בשכבות קודמות, בהתאם ללוגיקת המערכת והמדידה.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Hitback", "Previous Layer", "Current Layer"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "dtp",
    term: "DTP",
    abbreviation: "DTP",
    aliases: ["Down To Production"],
    fullName: "Down To Production",
    category: "systems",
    definition: "הוצאת Tool ממצב ייצור לצורך בדיקה, פעילות או Recovery.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Tool Restriction", "RFC", "Recovery"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "ucl",
    term: "UCL",
    abbreviation: "UCL",
    aliases: ["Upper Control Limit"],
    fullName: "Upper Control Limit",
    category: "systems",
    definition: "גבול בקרה עליון.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["OOC", "LCL", "Baseline"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "lcl",
    term: "LCL",
    abbreviation: "LCL",
    aliases: ["Lower Control Limit"],
    fullName: "Lower Control Limit",
    category: "systems",
    definition: "גבול בקרה תחתון.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["OOC", "UCL", "Baseline"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: false,
  },
  {
    id: "dcl",
    term: "DCL",
    abbreviation: "DCL",
    aliases: ["Disposition Control Limit"],
    fullName: "Disposition Control Limit",
    category: "systems",
    definition: "גבול בקרה המשמש לצורך החלטות Disposition בהתאם להגדרה המקומית והנוהל המאושר. Confirmed (Stage B.3, still SME-flagged): disposition threshold used during process monitoring and response decisions.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: true,
  },
  {
    id: "e3-abort",
    term: "E3 Abort",
    aliases: [],
    fullName: "E3 Abort",
    category: "systems",
    definition: "עצירת תהליך במהלך הריצה בעקבות פרמטר Tool או FDC שחצה תנאי מוגדר. Confirmed (Stage B.3): tool process interruption triggered by equipment or FDC parameters.",
    plainLanguage: "The run stopped automatically because a monitored parameter exceeded limits.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["FDC", "Tool Event", "QEF"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "qef",
    term: "QEF",
    abbreviation: "QEF",
    aliases: ["Quality Event Form"],
    fullName: "Quality Event Form",
    category: "systems",
    definition: "תיעוד של אירוע איכות הקשור ל-Tool, Defects, Process או פרמטר חריג. Confirmed (Stage B.3): formal quality event record used to document process, tool, yield, excursion, or non-POR events.",
    plainLanguage: "Official quality-event tracking record.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Quality Overview", "DRB", "Non-POR", "Excursion", "RFC"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "drb",
    term: "DRB",
    abbreviation: "DRB",
    aliases: ["Disposition Review Board"],
    fullName: "Disposition Review Board",
    category: "systems",
    definition: "פורום או תהליך סקירה לקבלת החלטת Disposition באירוע שאינו סטנדרטי. Confirmed (Stage B.3): review process used when material or process disposition requires cross-functional approval.",
    plainLanguage: "A decision meeting for unusual situations.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Disposition", "QEF", "TO3"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "tala",
    term: "TALA",
    abbreviation: "TALA",
    aliases: ["Tool Activation List Automation"],
    fullName: "Tool Activation List Automation",
    category: "systems",
    definition: "מערכת אוטומטית שמפעילה רצף פעולות על Tool בעקבות אירוע או Tracer, בהתאם להגדרה המאושרת. Confirmed (Stage B.3): automated system that executes predefined tool-response actions after tracer or recovery activity.",
    plainLanguage: "A system that automatically performs required steps on a tool.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Tracer", "RFC", "Recovery"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "os",
    term: "OS",
    abbreviation: "OS",
    aliases: ["Oversample", "Over Sample"],
    fullName: "Oversample",
    category: "systems",
    definition: "ביצוע מדידה נוספת או מורחבת כדי לקבל יותר נתונים ולשפר את הביטחון בתוצאה. Confirmed (Stage B.3): additional sampling beyond the standard measurement plan.",
    plainLanguage: "Taking extra measurements to increase confidence.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["Scan", "SS", "Tracer", "Monitor"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B3_ENGINEER_NOTES_SOURCE,
    ],
    needsReview: false,
  },
  {
    // fullName intentionally omitted: Stage B.3 instruction gave "NVD" as
    // both term and stated full-name text, but per governance rule 1
    // (never invent/assert an acronym expansion) this is treated as an
    // unresolved expansion, not a confirmed one. UI shows the
    // "Full Name Pending SME Verification" placeholder until an SME
    // confirms the real expansion. See docs/survival-guide-content-audit.md.
    id: "nvd",
    term: "NVD",
    abbreviation: "NVD",
    aliases: [],
    category: "process-manufacturing",
    definition: "Process-related abnormality that may not appear as a traditional visible defect but can influence defect behavior and yield impact. (Stage B.3, SME required: full-name expansion not yet confirmed.)",
    plainLanguage: "A process issue that can affect results even when SEM images look normal.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B3_ENGINEER_NOTES_SOURCE],
    needsReview: true,
  },
  {
    id: "multi-pass",
    term: "Multi Pass",
    aliases: [],
    fullName: "Multi Pass",
    category: "process-manufacturing",
    definition: "Condition where the same equipment participates in more than one operation in the manufacturing flow. (Stage B.3)",
    plainLanguage: "The wafer may visit the same tool multiple times during processing.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B3_ENGINEER_NOTES_SOURCE],
    needsReview: false,
  },
  {
    id: "ss",
    term: "SS",
    abbreviation: "SS",
    aliases: ["Surf Scan", "Surface Scan"],
    fullName: "Surface Scan",
    category: "systems",
    definition: "סריקה של פני השטח של Wafer לצורך איתור Defects. Confirmed (Stage B.1): inspection scan of the wafer surface used to search for defect candidates.",
    plainLanguage: "The inspection step where the tool looks for defects on the wafer.",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["SM", "MSS", "Monitor Wafer"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
      STAGE_B1_SME_SOURCE,
    ],
    needsReview: false,
  },
  {
    id: "sqc",
    term: "SQC",
    abbreviation: "SQC",
    aliases: ["Spin Quality Check"],
    fullName: "Spin Quality Check",
    category: "systems",
    definition: "בדיקת איכות הקשורה לפעילות Spin, בהתאם להגדרת המודול והנוהל הרלוונטי.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: [],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [
      {
        sourceType: 'sme-curated',
        fileName: GLOSSARY_SOURCE_FILE,
        sitePath: 'local-source-materials/terminology/' + GLOSSARY_SOURCE_FILE,
        accessOutcome: 'accessible-fully-read',
      },
    ],
    needsReview: true,
  },
  {
    id: "ncdd",
    term: "NCDD",
    abbreviation: "NCDD",
    aliases: ["Normalized Cluster Defect Density"],
    fullName: "Normalized Cluster Defect Density",
    category: "yield-defect",
    definition: "Confirmed (Stage B.1): normalized density metric based on clustered defects.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["CDD", "EDI", "Defect Count"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B1_SME_SOURCE],
    needsReview: false,
  },
  {
    id: "cdd",
    term: "CDD",
    abbreviation: "CDD",
    aliases: ["Cluster Defect Density"],
    fullName: "Cluster Defect Density",
    category: "yield-defect",
    definition: "Confirmed (Stage B.1): density metric based on spatially clustered defects.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["NCDD", "EDI", "Defect Count"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B1_SME_SOURCE],
    needsReview: false,
  },
  {
    id: "ars",
    term: "ARS",
    abbreviation: "ARS",
    aliases: ["Advanced Review Sampling"],
    fullName: "Advanced Review Sampling",
    category: "measurement-analysis",
    definition: "Confirmed (Stage B.1): system that assigns review samples and sample bins.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["ADC", "DOR", "Classification"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B1_SME_SOURCE],
    needsReview: false,
  },
  {
    id: "ymc",
    term: "YMC",
    abbreviation: "YMC",
    aliases: ["Yield Model Calculator"],
    fullName: "Yield Model Calculator",
    category: "yield-defect",
    definition: "Confirmed (Stage B.1): engine that assigns kill probabilities and contributes to EDI calculation.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["EDI"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B1_SME_SOURCE],
    needsReview: false,
  },
  {
    id: "dor",
    term: "DOR",
    abbreviation: "DOR",
    aliases: ["Defect Offline Review Station"],
    fullName: "Defect Offline Review Station",
    category: "measurement-analysis",
    definition: "Confirmed (Stage B.1): defect review classification station.",
    plainLanguage: "",
    whyItMatters: "",
    dailyWorkContext: [],
    whereYouWillSeeIt: [],
    relatedTerms: ["ADC", "ARS", "Classification"],
    roleScope: [],
    processScope: [],
    stableOrProcedural: 'mixed',
    verificationStatus: 'SME-curated',
    sources: [STAGE_B1_SME_SOURCE],
    needsReview: false,
  },
];

export const SME_CURATED_GLOSSARY_ENTRIES_BY_ID = new Map(
  SME_CURATED_GLOSSARY_ENTRIES.map((e) => [e.id, e]),
);
